### ISSUE TITLE
Artist, Album, and Song,  not showing with new Plex Update

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying#24] opened 2018-11-05 14:21 UTC
Plex updated and not Showing text for Artist, Album or Song.
even Rainmeter is not showing names for either one using your plugin

**Comment by tjhrulz** [comment] 2019-03-27 23:16
Duplicate of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/22 given that that is posted on the extension which is the right place I will leave that one open.

**Closed by tjhrulz** 2019-03-27 23:16 UTC
