### ISSUE TITLE
Add support for jellyfin

### ISSUE THREAD

**Issue by maxrioux100** [tjhrulz/WebNowPlaying#58] opened 2021-01-24 21:26 UTC
Hello, i'm using the web interface of jellyfin. I would greatly apreciate if the script would be compatible with it. Right now, it is partially working with the generic script. The time for the song is working, the album picture isn't and the song title show as Jellyfin instead of the title. 

Thanks you, tell me if I can help you in any way.

**Comment by tjhrulz** [comment] 2021-05-08 23:16
Duplicate of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/73 and given that that is in the relevant source code repo this is being closed

**Closed by tjhrulz** 2021-05-08 23:16 UTC
